#!/bin/bash

echo -n "Type a digit or a letter > "
read character
case $character in
				    # Checking for letters
	[[:lower:]] | [[:upper:]] ) echo "You typed the letter $character"
				    ;;

				    # Checking for digits
	[0-9] ) 		    echo "You typed the digit $character"
				    ;;

				    # Checking for anything else
	* )			    echo "You did not type a letter or a digit"
esac				    
