#!/bin/bash

##### Shell script While loop

#number=0
#while [ "$number" -lt 10 ]; do
#	echo "Number = $number"
#	number=$((number + 1))
#done

##### Shell script Until loop

#number=0
#until [ "$number" -ge 10 ]; do
#	echo "Number = $number"
#	number=$((number + 1))
#done

##### Shell script For loop

#for i in word1 word2 word3; do
#	echo $i
#done

#count=0
#for i in $(cat ~/.bash_profile); do
#	count=$((count + 1))
#	echo "Word $count ($i) contains $(echo -n $i | wc -c) characters"
#done

# Loop through positional parameters

#for i in "$@"; do
#	echo $i
#done

for filename in "$@"; do
	result=
	if [ -f "$filename" ]; then
		result="$filename is a regular file"
	else
		if [ -d "$filename" ]; then
			result="$filename is a directory"
		fi
	fi
	if [ -w "$filename" ]; then
		result="$result and it is writable"
	else
		result="$result and it is not writable"
	fi
	echo "$result"
done
