#!/bin/bash

# Program to print a text file with headers and footers
# (For now will just echo the contents of the file)

TEMP_FILE=/tmp/printfile.txt

# The trap command listens for the three signals specified and then runs the   
# commands in quotes

trap "rm $TEMP_FILE; exit" SIGHUP SIGINT SIGTERM

pr $1 > $TEMP_FILE

echo -n "Print file? [y/n]: "
read
if [ "$REPLY" = "y" ]; then
	cat $TEMP_FILE
fi

# Last command is to remove the temp file when the script is done if no signal 
# triggers the trap command

rm $TEMP_FILE
