#!/bin/bash

# Program to print a text file with headers and footers
# (For now will just echo the contents of the file)

TEMP_FILE=/tmp/printfile.txt

clean_up() {
	# Perform program exit housekeeping
	rm $TEMP_FILE
	exit
}

# The trap command listens for the three signals specified and then runs the   
# commands in quotes

trap clean_up SIGHUP SIGINT SIGTERM

pr $1 > $TEMP_FILE

echo -n "Print file? [y/n]: "
read
if [ "$REPLY" = "y" ]; then
	cat $TEMP_FILE
fi

clean_up
